import subprocess
import json
import statistics
import sys
import random

# Example test set (extend to 100+ words)
TEST_WORDS = [
    'Advisory Circular',
'Air Operator Certificate',
'Aircraft Operating Manual',
'Aircraft Operating Manual',
'Aircraft Operating Manual',
'Civil Aviation Authority of Botswana',
'Crew Scheduling Manual',
'Cabin Crew Manual',
'Flight Crew Operating Manual',
'Flight Operations Manual',
'Flight Operations Training Manual',
'International Civil Aviation Organization',
'Maintenance Control Manual',
'Minimum Equipment List',
'Maintenance Organization Exposition Manual',
'Maintenance Organization’s Procedures Manual',
'Maintenance Training Manual',
'Station Operations Manual',
'Standard Operating Procedures',
'a required',
'above aerodrome elevation',
'above field elevation',
'above ground level',
'above mean sea level',
'above sea level',
'accelerate stop distance available',
'acceptable deferred defect',
'acceptable mean of compliance',
'accessory',
'accessory gear box',
'act',
'active clearance control',
'active electronically scanned array',
'active noise cancellation',
'active noise reduction',
'activematrix liquidcrystal display',
'actual time of departure',
'actuator control electronics',
'adjust vertical speed adjust',
'adjustment',
'advanced qualification program',
'advanced surface movement guidance and control system',
'advanced technology engine',
'advisory area',
'advisory circular',
'aerodrome',
'aerodrome operating minimum',
'aerodrome reference point',
'aerodrome traffic frequency',
'aeronautical decisionmaking',
'aeronautical fixed service',
'aeronautical fixed telecommunication network',
'aeronautical information exchange model',
'aeronautical information manual',
'aeronautical information publication',
'aeronautical information regulation and control',
'aeronautical information service',
'aeronautical national pipe taper',
'aeronautical operational control',
'aeronautical radio inc',
'aeronautical satellite data link',
'aeronautical telecommunication network',
'aeroplane',
'aft the direction against the aircraft movement',
'air accident investigation bureau',
'air condition unit',
'air cycle machine',
'air data attitude heading reference system',
'air data computer',
'air data inertial reference system',
'air data inertial reference unit',
'air data module',
'air data system',
'air defense identification zone',
'air management system',
'air navigation service provider',
'air oil',
'air operator certificate',
'air route traffic control center',
'air to air tacan function',
'air traffic control',
'air traffic control centre',
'air traffic control radar beacon system',
'air traffic control signalling system',
'air traffic control tower',
'air traffic controller',
'air traffic flow management',
'air traffic management',
'air traffic service',
'air traffic service unit',
'air transport action group',
'air transport association',
'air transportable racking',
'airborne collision avoidance system',
'airborne flight information system',
'airborne separation assurance system',
'airborne traffic situational awareness',
'airborne warning and control system',
'airbus',
'aircraft',
'aircraft autonomous integrity monitoring',
'aircraft communication addressing and reporting system',
'aircraft condition monitoring system',
'aircraft continuous airworthiness monitoring',
'aircraft data network',
'aircraft flight manual',
'aircraft integrated data system',
'aircraft maintenance engineer',
'aircraft maintenance manual',
'aircraft maintenance program',
'aircraft maintenance technician',
'aircraft nose down',
'aircraft on ground',
'aircraft operation manual',
'aircraft personality module',
'aircraft security logging overview',
'aircraft situation display',
'airground communication facility',
'airground data link',
'airline network architecture',
'airline transport pilot licence',
'airman certification standard',
'airmissions meteorological advisory',
'airplane',
'airplane upset prevention recovery training aid',
'airport',
'airport advisory service',
'airport council international',
'airport network security operator guidance',
'airport of arrival',
'airport of departure',
'airport operating plan',
'airport reservation office',
'airport surface detection equipment',
'airport surveillance radar',
'airport traffic control tower',
'airspace management',
'airspeed indicator',
'airworthiness directive',
'airworthiness limitation item',
'airworthiness review',
'airworthiness review certificate',
'all weather operation',
'alternate',
'alternative configuration tool',
'alternative training and qualification programme',
'alternator control unit',
'altimeter',
'altitude',
'altitude hold mode',
'altitude select',
'altocumulus',
'altocumulus castellanus',
'aluminum',
'american wire gage',
'and interference',
'and tcas reporting',
'angle of attack',
'annunciator panel',
'antenna',
'antiskid',
'appendix',
'application',
'approach control',
'approach lighting system',
'approach procedure with vertical guidance',
'approved maintenance organization',
'approved training organisation',
'approximately',
'arbeitsgemeinschaft deutscher verkehrsflughfen',
'area control centre',
'area navigation',
'assembly',
'assign',
'association of european airline',
'assumed adverse obstacle',
'attitude',
'attitude and heading reference system',
'attitude and positioning inertial reference system',
'attitude director indicator',
'attitude heading control',
'audio control panel',
'audio control system',
'authorization of aircraft network security program',
'authorization required',
'auto pilot computer',
'auto pilot system',
'autofeather',
'automated surface observation system',
'automated weather observation system',
'automatic carrier landing system',
'automatic dependent surveillance',
'automatic direction finder',
'automatic flight control system',
'automatic gain control',
'automatic groundair communication system',
'automatic level control',
'automatic pressure altitude reporting system',
'automatic takeoff thrust control system',
'automatic terminal information service',
'automatic thrust restoration',
'autopilot',
'autopilot flight director',
'autopilot flight director computer',
'autopilot flight director system',
'autothrottle',
'autothrust',
'auxiliary power unit',
'available',
'available seat mile',
'aviation electronics',
'aviation medical examiner',
'aviation weather briefing service',
'aviation weather information service',
'aviation weather web site',
'avionic communication router',
'avionics fullduplex switched ethernet',
'avionics switching unit',
'back course',
'balanced field length',
'barely visible impact damage',
'barometric indication',
'barometric vertical navigation',
'basic area navigation',
'bearing distance indicator',
'belgian civil aviation authority',
'beyond economic repair',
'beyond visual range',
'biennial flight review',
'bill of material',
'bird watch condition',
'blue print',
'board',
'bottom dead centre',
'brake horsepower',
'braketovacate system',
'branch',
'bridge mounted equipment',
'broadcast global area network',
'builtin test equipment',
'butt line',
'bypass ratio',
'cabin air conditioning and temperature control system',
'cabin attendant panel',
'cabin service system',
'calibrated airspeed',
'canada',
'canadian aviation regulation',
'captain',
'carbon offsetting and reduction scheme for international aviation',
'cathoderay tube',
'caution advisory panel',
'certificate of airworthiness',
'certification specification',
'changed product rule',
'civil air navigation service organisation',
'civil aviation authority',
'civil aviation regulation',
'closest point of approach',
'cockpit area microphone',
'cockpit voice and digital flight data recorder',
'cockpit voice recorder',
'coder',
'collins standard digital bus',
'combination navigation and communication equipment',
'command and control',
'commentresponse document',
'commercial air service standard',
'commercial offtheshelf',
'commercial standard digital bus',
'common traffic advisory frequency',
'communication',
'communication receiver',
'communication transceiver',
'compass deviation',
'condition monitored component',
'configuration item signer crater tool',
'constant speed drive',
'constant speed unit',
'continuing airworthiness management exposition',
'continuing airworthiness management organisation',
'continuing analysis and surveillance system',
'continuous airworthiness maintenance program',
'control wheel steering',
'control zone',
'controlled traffic region',
'controller area network',
'controllerpilot data link communication',
'corrosion resistant steel',
'crew resource management',
'crosscountry',
'crossstart',
'crosstrack',
'cycle per second',
'cycle since new',
'cycle since overhaul',
'damaged beyond economic repair',
'dangerous good regulation',
'data recorder',
'data transfer unit',
'datalink control and display unit',
'datalink recorder',
'dead reckoning',
'decide',
'decision altitude',
'decision height',
'declared training organisation',
'decoder',
'deferred maintenance item',
'degraded visual environment',
'density altitude',
'departure clearance via cpdlc',
'departure end of runway',
'departure procedure',
'design approval holder',
'design organization',
'design organization approval',
'design organization manual',
'designated engineering representative',
'designated mechanic examiner',
'deutsches zentrum fr luft und raumfahrt ev',
'diagnose',
'diameter',
'differential gps',
'digital expandable flight data acquisition and recording system',
'digital flight data recorder',
'digital signal processing',
'direct noise canceling',
'direct reading magnetic compass',
'direct user access terminal service',
'directional gyro',
'directional gyroscope',
'dispatch deviation guide',
'display control panel',
'display electronic unit',
'display processor unit',
'distance measuring equipment',
'downlink of aircraft parameter',
'drift angle',
'dry operational weight',
'dual frequency multiple constellation',
'effective translational lift',
'electric motor driven pump',
'electronic attitude direction indicator',
'electronic centralised aircraft monitor',
'electronic engine control',
'electronic flight bag',
'electronic flight display',
'electronic flight instrument system',
'electronic horizontal situation indicator',
'electronic instrument system',
'electronic noise canceling',
'electronic noise reduction',
'elevator and aileron computer',
'elevator feel shift',
'embedded gps inertial',
'emergency locator transmitter',
'emergency power unit',
'emergency safe altitude',
'emergency vision assurance system',
'empty weight',
'en route automation modernization',
'end of civil evening twilight',
'engine',
'engine buildup',
'engine control unit',
'engine failure flap retraction altitude',
'engine failure on takeoff',
'engine failure procedure',
'engine flight cycle',
'engine flight hour',
'engine health monitoring',
'engine pressure ratio',
'engineered material arresting system',
'engineering authorisation',
'engineering bill of material',
'engineering change request',
'engineering control also e',
'engineering data record',
'engineering request for maintenance',
'engineindicating and crewalerting system',
'enhanced flight visual system',
'enhanced ground proximity warning system',
'enhanced surveillance',
'enhanced vision system',
'enhanced vision system instrument',
'enroute surveillance radar',
'environmental control system',
'equivalent airspeed',
'equivalent level of safety',
'estimated elapsed time',
'estimated offblocktime',
'estimated time en route',
'estimated time of arrival',
'estimated time of departure',
'european aviation safety agency',
'european geostationary navigation overlay service',
'european network of civil aviation safety investigation authority',
'european organisation for civil aviation equipment',
'european part approval',
'european technical standard order',
'exhaust gas temperature',
'expect further clearance',
'expected approach time',
'experimental lightsport aircraft',
'extended diversion time operation',
'extendedrange twinengine operation performance standard',
'facility directory',
'federal aviation administration',
'federal aviation regulation',
'federal inspection service',
'filed flight plan',
'final approach and take off',
'final approach course',
'final approach course fix',
'final approach fix',
'final approach point',
'final approach runway occupancy signal',
'final approach segment',
'final end point',
'first available flight',
'first officer',
'fixed base simulator',
'fixedbase operator',
'flight attendant',
'flight augmentation computer',
'flight control computer',
'flight control system',
'flight crew',
'flight crew operating manual',
'flight crew training manual',
'flight data monitoring',
'flight data recorder',
'flight data recorder system',
'flight director',
'flight duty period',
'flight duty time limitation',
'flight guidance',
'flight information centre',
'flight information region',
'flight information service',
'flight information service enroute',
'flight into known icing',
'flight level',
'flight management and guidance computer',
'flight management computer',
'flight management system',
'flight mode annunciator',
'flight operation officer',
'flight operational quality assurance',
'flight path angle',
'flight plan data processing system',
'flight safety foundation',
'flight service station',
'flight standard district office',
'flight standard information management system',
'flight time limitation',
'flight training device',
'flight warning system',
'flightdata acquisition unit',
'flux detector unit',
'flux valve unit',
'flybywire',
'fog investigation and dispersal operation',
'foot per minute',
'foreign object damage',
'forward attendant panel',
'forwardlooking infrared',
'forwardlooking terrain avoidance',
'free air temperature',
'free fall drop zone',
'frequency',
'frequency modulation',
'fuel control monitoring computer',
'fuel control unit',
'fuel flow',
'fuel onboard',
'fuel quantity indication system',
'full approach lighting system',
'full authority digital engine control',
'full flight simulator',
'functional flight check',
'fuselage station',
'future air navigation system',
'gas',
'gbas approach service type',
'gbas landing system',
'general aviation',
'general maintenance manual',
'general practice and procedure',
'generator control unit',
'geometric dilution of precision',
'german aerospace center',
'gigahertz',
'ginduced loss of consciousness',
'glide path',
'glider snatch pickup',
'glideslope',
'global navigation air data inertial reference system',
'global navigation air data inertial reference unit',
'global navigation satellite system',
'global positioning system',
'global positioning system ground station',
'goaround',
'goaround switch',
'gps landing and navigation system',
'gps landing and navigation unit',
'gps landing unit',
'gps precision code',
'greenwich mean time',
'gross shop processing time',
'ground',
'ground based augmentation system',
'ground collision avoidance system',
'ground effect area',
'ground power unit',
'ground proximity warning system',
'ground support equipment',
'groundbased',
'groundcontrolled approach',
'groundspeed',
'guidance material',
'hand on throttle and stick',
'hazardous inflight weather advisory service',
'hazardous material',
'heading',
'heading hold',
'heading select',
'headup display',
'headwind',
'health and usage monitoring system',
'heavy',
'height',
'height above airport',
'height above touchdown',
'height loss',
'helmetmounted display',
'hertz',
'high',
'high bandwidth connectivity system',
'high frequency',
'high intensity radio transmission area',
'high intensity runway lighting',
'high intensity runway operation',
'high pressure compressor',
'high pressure rotor',
'high pressure turbine',
'high pressure turbine active clearance control',
'highspeed data',
'hold',
'horizontal deviation bar',
'horizontal deviation indicator',
'horizontal dilution of precision',
'horizontal situation indicator',
'hover in ground effect',
'hover out of ground effect',
'human factor and ergonomics society',
'human factor engineering',
'human remains',
'humanpowered aircraft',
'hydraulic',
'hydraulic interface module',
'hydraulic motor generator',
'hydromechanical unit',
'icecontaminated tailplane stall',
'identification friend or foe',
'identification or identifier',
'identifier',
'identify',
'idle cutoff',
'ie altitude above msl',
'illustrated part catalog eg by boeing',
'inboard',
'inch of mercury',
'indicated airspeed',
'indicator',
'inertial navigation system',
'inertial reference system',
'inertial reference unit',
'inflight entertainment',
'inflight landing distance',
'inflight shutdown',
'information display system',
'initial approach fix',
'initial release',
'inlet guide vane',
'inside mold line',
'instantaneous vertical speed indicator',
'instruction for continuous airworthiness',
'instrument approach chart',
'instrument approach procedure',
'instrument flight procedure',
'instrument flight rule',
'instrument landing system',
'instrument meteorological condition',
'instrument rating test',
'instrumented runway visual range',
'integrated approach navigation',
'integrated drive generator',
'integrated engine pressure ratio',
'integrated flight instrument and control system',
'integrated standby flight display',
'integrated standby instrument system',
'integrated switching panel',
'interactive electronic technical manual',
'interface control document',
'intermediate approach fix',
'international air transport association',
'international civil aviation organization',
'international council of the aeronautical science',
'international federation of air traffic controller association',
'international federation of airworthiness',
'international standard atmosphere',
'international traffic in arm regulation',
'interstage turbine temperature',
'intrusion',
'issued by easa see tso',
'jamming',
'joint aviation authority',
'joint aviation requirement',
'joint tactical information distribution system',
'key risk element',
'knot calibrated airspeed',
'knot indicated airspeed',
'knot true airspeed',
'land and hold short operation',
'land and marine',
'landing distance available',
'landing distance required',
'landing threshold point',
'landing weight',
'landing zone',
'large air tanker',
'last known position',
'lateral navigation',
'left hand seat',
'letter of authorization',
'licensed aircraft maintenance engineer',
'life limited component',
'life limited part',
'light',
'lightemitting diode',
'lightning',
'limitation of movement',
'line training captain',
'lineoriented flight training',
'linereplaceable unit',
'liquid crystal display',
'live human organ',
'load classification group',
'load classification number',
'load reduction device',
'loadable software aircraft part',
'loading instruction report',
'local area augmentation system',
'local area differential global positioning satellite',
'local area differential gps',
'localizer',
'localizer performance with vertical guidance',
'localizer type directional aid',
'location of passenger accommodation',
'locator middle marker',
'locator outer marker',
'long range cruise',
'longitudinal stability augmentation system',
'longrange navigation',
'loss of control',
'loss of control inflight',
'loss of tail rotor effectiveness',
'loss of thrust control',
'low instrument flight rule',
'low pressure compressor',
'low pressure rotor',
'low pressure turbine',
'low pressure turbine active clearance control',
'low visibility procedure',
'lowcost carrier',
'magnetic heading',
'magnetic variation',
'main base check',
'main landing gear',
'maintenance',
'maintenance and repair organization',
'maintenance deferred defect record',
'maintenance laptop',
'maintenance organisation exposition',
'maneuvering characteristic augmentation system',
'manifold absolute pressure',
'manifold pressure',
'manual of air traffic service',
'manual of word abbreviation',
'manufacturer certificate holder',
'manufacturing engineer',
'marginal visual flight rule',
'marker beacon',
'master minimum equipment list',
'material resource planning',
'material review board',
'material safety data sheet',
'max structural landing weight',
'max structural takeoff weight',
'max structural zero fuel weight',
'maximum continuous thrust',
'maximum elevation figure',
'maximum landing weight',
'maximum ramp weight',
'maximum structural cruising speed',
'maximum takeoff weight',
'maximum zero fuel weight',
'meaconing',
'mean aerodynamic chord',
'mean cycle between failure',
'mean sea level',
'mean time between failure',
'mean time between shop visit',
'mean time between unscheduled removal',
'mean time to failure',
'medical evacuation',
'medium',
'medium frequency',
'message',
'meteorological aerodrome report',
'microphone',
'microwave landing system',
'midair collision',
'middle marker',
'military operation area',
'military specification',
'minimum aviation performance standard',
'minimum control speed with critical engine out',
'minimum descent altitude',
'minimum descent height',
'minimum enroute altitude',
'minimum equipment list',
'minimum flap retraction altitude',
'minimum navigation performance specification',
'minimum obstacle clearance altitude',
'minimum off route altitude',
'minimum operational performance standard',
'minimum runway occupancy time',
'minimum safe altitude',
'minimum sector altitude',
'minimum stabilization distance',
'minimum vectoring altitude',
'missed approach holding fix',
'missed approach point',
'mixture',
'mode control panel',
'mode s transponder',
'mode sspecific protocol',
'mode sspecific service',
'model x',
'modular open system architecture',
'moving map display',
'multi control display unit',
'multicrew cooperation',
'multicrew pilot license',
'multidisciplinary measure',
'multiengine piston',
'multifunction control display unit',
'multifunction display',
'multifunction display system',
'multifunction keypad',
'multifunction processor unit',
'multifunctional information distribution system',
'national airspace system',
'national center for aircraft technician training',
'national center for aviation training',
'national institute of standard and technology',
'national transportation safety board',
'nautical mile',
'navigation and surveillance',
'navigation display',
'navigation receiver',
'navigation satellite timing and ranging',
'navigational aid',
'netherlands aerospace research centre',
'never exceed speed',
'next higher assembly',
'nightvision device',
'nitrogen generation system',
'no fault found',
'no radio',
'no tail rotor',
'noise abatement departure procedure',
'noise reduction rating',
'nondestructive testing',
'nondirectional beacon',
'nonnormal checklist',
'nonnormal maneuver boeing qrh',
'nonprecision approach',
'nonroutine task card',
'normal operating zone',
'north american aerospace defense command',
'nose landing gear',
'notice of proposed amendment',
'notice of proposed rulemaking',
'notice to air mission',
'notice to airman',
'notransgression zone',
'obstacle assessment surface',
'obstacle clearance altitude',
'obstacle clearance height',
'obstacle free zone',
'obstacle identification surface',
'omnibearing indicator',
'omnibearing selector',
'on condition',
'on request',
'onboard network access terminal',
'onboard network system',
'one engine inoperative',
'operating empty weight',
'operating weight empty',
'operation control center',
'operational check',
'operational information system',
'operational landing distance',
'operational performance category',
'operational weight',
'option',
'or communication radio transmitter',
'original equipment manufacturer',
'out of service',
'outer marker',
'outer mold line',
'outlet guide vane',
'outside air temperature',
'overcome by event',
'overhaul',
'overhaul manual',
'parachute jumping area',
'parachute jumping exercise',
'part manufacturer approval',
'part number',
'passenger',
'passenger service unit',
'passenger step',
'passive electronically scanned array',
'passive noise reduction',
'pavement classification number',
'payload',
'performance degradation allowance',
'performance improvement package',
'performancebased communication and surveillance',
'performancebased navigation',
'permanent magnet generator',
'permit to fly',
'person on board',
'personnel and equipment working',
'phase of flight',
'pilot activated lighting',
'pilot automatic telephone weather answering service',
'pilot controlled lighting',
'pilot decision making',
'pilot flying',
'pilot in command',
'pilot induced oscillation',
'pilot monitoring',
'pilot not flying',
'pilot operating handbook',
'pilot report',
'pilot training record',
'place bearing distance',
'point of equal time',
'point of no return',
'point of safe return',
'point takeoff and landing',
'position',
'position dilution of precision',
'power drive unit',
'power management computer',
'power supply reset',
'power transfer control unit',
'pre aircraft on ground',
'precision approach path indicator',
'precision approach radar',
'precision final approach fix',
'predeparture clearance',
'prerecorded announcement',
'pressure altitude',
'primary flight display',
'primary navigation display',
'primary surveillance radar',
'principal maintenance inspector',
'principle of flight',
'prior permission required',
'private pilot licence',
'procedure design gradient',
'procedure for air navigation service',
'product support and assurance agreement',
'production approval holder',
'production organisation approval',
'proficiency check',
'profile descent',
'prohibited airspace',
'propeller',
'protective breathing equipment',
'proximity switch electronic unit',
'public address system',
'public domain aeronautical software',
'push to talk',
'quality and compliance monitoring',
'quick access recorder',
'quick engine change',
'quick reaction alert',
'quick reference handbook',
'quiet takeoff and landing',
'radar',
'radar data processing system',
'radar or radio altimeter',
'radio altimeter indicator',
'radio altitude',
'radio altitude or radar altimeter',
'radio detection and ranging',
'radio distance magnetic indicator',
'radio frequency',
'radio frequency interference',
'radio magnetic indicator',
'radio management panel',
'radio receiver',
'radiotelephony',
'ram air turbine',
'ramp weight',
'range',
'rate of climb',
'rate of descent',
'receiver',
'receiver autonomous integrity monitoring',
'recreational flight instructor',
'recreational pilot licence',
'rectified air speed',
'reduced horizontal separation minimal',
'reduced takeoff and landing',
'reduced vertical separation minimum',
'reduction gear box',
'reference',
'reference datum height',
'regular public transport',
'regulatory impact assessment',
'regulatory takeoff weight',
'rejected takeoff',
'relative',
'relay',
'remaining life time cycle',
'remote airport advisory service',
'remote communication outlet',
'remotely piloted aircraft',
'remotely piloted aircraft system',
'repair',
'repair engineering order',
'repetitive flight planning',
'required',
'required inspection item',
'required navigation performance',
'rescue and fire fighting',
'resolution advisory',
'restricted airspace',
'restricted area',
'return to base',
'reverse current relay',
'reversion switch panel',
'review',
'revolution per minute',
'right hand seat',
'ring laser gyroscope',
'rotary variable differential transformer',
'route',
'rudder travel limiting',
'rule making task',
'runway',
'runway awareness and advisory system',
'runway end identifier light',
'runway end safety area',
'runway safety area',
'runway threshold',
'runway visual range',
'safety and emergency procedure',
'safety management document',
'satellite communication',
'satellite data unit',
'satellite interface unit',
'satellite navigation',
'satellitebased augmentation system',
'search and rescue',
'seat belt',
'secondary surveillance radar',
'secure digital',
'see tailplane',
'selective calling',
'senior cabin crew member',
'senior first officer',
'serial number',
'service bulletin',
'service manual',
'setting or pressure',
'short field performance',
'short messaging service',
'short takeoff and landing',
'shortterm conflict alert',
'signaltonoise ratio',
'significant meteorological information',
'simplified directional facility',
'simultaneous opposite direction parallel runway operation',
'since major overhaul',
'single european sky atm research',
'single lever power control',
'singleengine piston',
'slat flap control computer',
'smart acms recorder',
'software maintenance tool',
'software tool',
'solidstate cockpit voice',
'solidstate cockpit voice recorder',
'solidstate flight data recorder',
'speaker',
'special condition',
'special event search and master analysis',
'special flight operating certificate',
'special operation force',
'special operation group',
'special use airspace',
'special visual flight rule',
'specific assurance and integrity level',
'speed for best angle of climb',
'speed for best rate of climb',
'speed over ground',
'speed reference system',
'speed trim system',
'squelch',
'stability augmentation system',
'stall protection system',
'stall speed in landing configuration',
'standard computerized airplane performance',
'standard instrument departure',
'standard operating procedure',
'standard temperature and pressure',
'standard terminal arrival route',
'standard terminal automation replacement system',
'start of climb at missed approach',
'statement of work',
'static air temperature',
'strategic lateral offset procedure',
'stratus fractus',
'structural repair manual',
'sunrise',
'sunset',
'supplemental type certificate',
'surface movement radar',
'surveillance approach radar',
'sustainable aviation fuel',
'switch',
'synthetic vision guidance system',
'tacan',
'tachometer',
'tactical air navigation',
'tail rotor',
'tail wind component',
'takeoff',
'takeoff and landing performance assessment aviation rule committee',
'takeoff distance available',
'takeoff power',
'takeoff runway',
'takeoff runway available',
'takeoff warning system',
'takeoff weight',
'target',
'taxiway',
'tcas ii transmitter',
'technical logbook',
'technical standard order',
'telecommunication control unit',
'temperature',
'temporary flight restriction',
'temporary guidance leaflet',
'temporary reserved area',
'terminal aerodrome forecast',
'terminal approach radar',
'terminal arrival altitude',
'terminal arrival area',
'terminal control area usa',
'terminal doppler weather radar',
'terminal instrument procedure',
'terminal manoeuvring area',
'terminal radar approach control',
'terminal weather information for pilot',
'terminal weather radar',
'terminal wireless lan unit',
'terrain awareness and warning system',
'terrain awareness display',
'terrain clearance floor',
'the qcode for altimeter subscale setting to obtain elevation when on the ground',
'the qcode for atmospheric pressure at aerodrome elevation',
'the qcode for pressure altitude',
'thermal antiice',
'thinfilm transistor',
'threeletter acronym',
'threshold',
'threshold crossing height',
'throttle control assembly',
'thrust',
'thrust asymmetry compensation',
'thrust computer indicator',
'thrust lever angle',
'thrust rating panel',
'thrust reverser',
'time between overhaul',
'time dilution of precision',
'time since last overhaul',
'time since new',
'time to station',
'timelimited dispatch',
'toolbox mobile library',
'top of climb',
'top of descent',
'total air temperature',
'total airport management',
'total time air frame',
'total time since new',
'total time since overhaul',
'total vertical error',
'touchandgo landing',
'touchdown zone',
'touring motor glider',
'towering cumulus',
'track',
'track angle',
'trackangle error',
'traffic',
'traffic advisory',
'traffic collision avoidance system',
'traffic information service',
'traffic pattern altitude',
'transceiver',
'transcribed weather broadcast',
'transfer',
'transfer gearbox',
'transformer rectifier',
'transient bleed valve',
'transition',
'transmission',
'transmit',
'transmitter',
'transmitter receiver or transceiver',
'transponder',
'transponder code',
'transponder code and altitude reporting',
'transponder landing system',
'transponder mandatory zone',
'transponder pulsecode reporting',
'transport canada',
'transport canada civil aviation',
'trimmable horizontal stabilizer',
'true airspeed',
'true course',
'true heading',
'tuned to localizer',
'turbine gas temperature',
'turbine inlet temperature',
'turbine outlet temperature',
'turn coordinator',
'turning point at missed approach',
'twoway data link',
'type certificate',
'type certificate data sheet',
'type rating examiner',
'ultrahigh frequency',
'under supervision',
'undercarriage',
'underwater locator beacon',
'universal asynchronous receivertransmitter',
'universal communication',
'universal serial bus',
'universal time coordinated',
'unlimited',
'unmanned aerial vehicle',
'unmanned aircraft system',
'upper area control',
'upper information region',
'upper wind and temperature forecast',
'upset prevention and recovery training',
'variable bleed valve',
'variable inlet guide vane',
'variable speed constant frequency',
'variable stator vane',
'variablefrequency oscillator',
'variation',
'vehicle control service',
'vertical gyroscope',
'vertical navigation',
'vertical path',
'vertical path approach',
'vertical separation limit',
'vertical speed',
'vertical speed indicator',
'vertical takeoff and landing',
'vertical track',
'vertical velocity indicator',
'very high frequency',
'vfr navigation chart',
'vfr terminal area chart',
'vhf data link',
'vhf digital radio',
'vhf directionfinding',
'vhf navigation receiver',
'vhf omnidirectional range',
'video graphic array',
'video vision',
'visible impact damage',
'visual approach slope indicator',
'visual control room',
'visual descent point',
'visual flight rule',
'visual guidance lighting system',
'visual meteorological condition',
'visual point of reference',
'voice generator module',
'voice transmission',
'volt or voltage',
'voltage regulator',
'voltagestanding wave ratio',
'vor',
'vor and tacan combination',
'vor marker beacon',
'vor with distance measuring equipment',
'vortex generator',
'vortex ring state',
'wake turbulence category',
'war emergency power',
'waterline',
'waypoint',
'weather',
'weather message switching center',
'weather message switching center replacement',
'weather radar report',
'weather radar system',
'weight',
'weight balance',
'weightoffwheels',
'weightonwheels',
'wide area augmentation system',
'widearea master station',
'wind aloft',
'wind correction angle',
'wind direction',
'wind shear',
'window of circadian low',
'wiring diagram manual',
'with effect from',
'world aeronautical chart',
'wxr indicator mount',
'wxr receiver transmitter',
'wxr waveguide adapter',
'yaw damper',
'yaw damper system',
'yaw or yaw angle',
'zerofuel time',
'zerofuel weight',
'zulu time',

]

sample = random.sample(TEST_WORDS, 100)

def run_solver(word, solver_path):
    # Build initial masked state
    pattern = "".join("_" if c != " " else " " for c in word)
    input_json = {
        "hiddenWord": word,
        "currentWordState": pattern,
        "guessedLetters": [],
        "guessesRemaining": 6
    }

    # Run solver in auto mode
    proc = subprocess.Popen(
        ["python", solver_path, "--auto"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )
    out, err = proc.communicate(json.dumps(input_json) + "\n")
    if err:
        print("Error:", err)
    try:
        return json.loads(out.strip().split("\n")[-1])  # last JSON line
    except Exception as e:
        print("Parse error:", out)
        return None

def summarize(results):
    total = len(results)
    successes = sum(1 for r in results if r and r["status"] == "success")
    avg_guesses = statistics.mean(
        len(r["history"]) for r in results if r
    )
    wrong_guesses = statistics.mean(
        sum(1 for h in r["history"] if h["guess"] not in r["hiddenWord"]) 
        for r in results if r
    )
    return {
        "totalWords": total,
        "successes": successes,
        "failures": total - successes,
        "successRate": successes / total,
        "avgGuesses": avg_guesses,
        "avgWrongGuesses": wrong_guesses
    }

if __name__ == "__main__":
    if len(sys.argv) < 2:
        solver_path = input("Enter path to solver file: ").strip()
    else:
        solver_path = sys.argv[1]

    results = []
    for w in sample:
        res = run_solver(w, solver_path)
        results.append(res)
        if res:
            print(f"Word: {w:20} -> {res['status']} in {len(res['history'])} guesses")
        else:
            print(f"Word: {w:20} -> ERROR")

    stats = summarize(results)
    print("\n=== SUMMARY ===")
    print(json.dumps(stats, indent=2))